In [67]:
import numpy as np

def qr_decomposition(matrix: np.matrix, normalised=False):
    rows = matrix.shape[0]
    cols = matrix.shape[1]
    q = np.zeros((rows, cols))
    r = np.zeros((cols, cols))
    
    for i in range(0, cols):
        v = matrix[:, i]
        
        final = np.array(v).ravel()
        for j in range(0, i):
            qj = np.array(q[:, j])
            v_dot_qj = np.dot(qj, v)
            qj_dot_qj = np.dot(qj, qj)
            coeff = v_dot_qj / qj_dot_qj
            coeff = np.array(coeff)[0, 0]
            final = final - (coeff * qj)
        
        if normalised:
            norm = np.linalg.norm(final)
            final = final / norm
        q[:, i] = final
        
    return q, r

m = np.matrix([
    [1, 0, 0], 
    [2, 1, 0],
    [1, 1, 3],
    [1, 1, 1],
])
print(m)
print(m.shape)
q, r = qr_decomposition(m, normalised=True)
print(q)
print("----")
qT = q.T
print(np.matmul(qT, q))
print(np.matmul(q, qT))

print("----")
print(
   qT[0].dot(qT[1]) 
)
print(
   qT[0].dot(qT[2]) 
)
print(
   qT[1].dot(qT[2]) 
)

[[1 0 0]
 [2 1 0]
 [1 1 3]
 [1 1 1]]
(4, 3)
[[ 0.37796447 -0.6761234   0.42163702]
 [ 0.75592895 -0.16903085 -0.42163702]
 [ 0.37796447  0.50709255  0.73786479]
 [ 0.37796447  0.50709255 -0.31622777]]
----
[[ 1.00000000e+00 -2.49800181e-16  5.55111512e-17]
 [-2.49800181e-16  1.00000000e+00  2.15781215e-16]
 [ 5.55111512e-17  2.15781215e-16  1.00000000e+00]]
[[ 0.77777778  0.22222222  0.11111111 -0.33333333]
 [ 0.22222222  0.77777778 -0.11111111  0.33333333]
 [ 0.11111111 -0.11111111  0.94444444  0.16666667]
 [-0.33333333  0.33333333  0.16666667  0.5       ]]
----
-2.220446049250313e-16
5.551115123125783e-17
1.942890293094024e-16
