In [ ]:
import numpy as np

def qr_decomposition(matrix: np.matrix, normalised=False):
    rows = matrix.shape[0]
    cols = matrix.shape[1]
    q = np.zeros((rows, cols))
    r = np.zeros((cols, cols))
    
    for i in range(0, cols):
        v = matrix[:, i]
        
        final = np.array(v).ravel()
        for j in range(0, i):
            qj = np.array(q[:, j])
            v_dot_qj = np.dot(qj, v)
            qj_dot_qj = np.dot(qj, qj)
            coeff = v_dot_qj / qj_dot_qj
            coeff = np.array(coeff)[0, 0]
            final = final - (coeff * qj)
        
        if normalised:
            norm = np.linalg.norm(final)
            final = final / norm
        q[:, i] = final
        
    return q, r

m = np.matrix([
    [1, 0, 0], 
    [2, 1, 0],
    [1, 1, 3],
    [1, 1, 1],
])
print(m)
print(m.shape)
q, r = qr_decomposition(m, normalised=True)
print(q)
print("----")
qT = q.T
print(np.matmul(qT, q))
print(np.matmul(q, qT))

print("----")
print(
   qT[0].dot(qT[1]) 
)
print(
   qT[0].dot(qT[2]) 
)
print(
   qT[1].dot(qT[2]) 
)

[[1 0 0]
 [2 1 0]
 [1 1 3]
 [1 1 1]]
(4, 3)
[[ 1.         -0.57142857  0.8       ]
 [ 2.         -0.14285714 -0.8       ]
 [ 1.          0.42857143  1.4       ]
 [ 1.          0.42857143 -0.6       ]]
----
[[7.00000000e+00 2.22044605e-16 0.00000000e+00]
 [2.22044605e-16 7.14285714e-01 1.39570895e-16]
 [0.00000000e+00 1.39570895e-16 3.60000000e+00]]
[[1.96653061 1.44163265 1.87510204 0.27510204]
 [1.44163265 4.66040816 0.81877551 2.41877551]
 [1.87510204 0.81877551 3.14367347 0.34367347]
 [0.27510204 2.41877551 0.34367347 1.54367347]]
----
2.220446049250313e-16
0.0
1.3877787807814457e-16
